@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI4MTc4NWZlLTcyZDEtNGEwYy04NDg2LTQ1OTZjMWNhNTNiYiIsImlhdCI6MTc2NDUzMDUzOSwiZXhwIjoxNzY0NTMxNDM5fQ.0ri66l9kgFSuZ7R5VUQL-kujIh3j8aU9mXRMrYl2PsY
GET {{baseUrl}}/news?page=1&limit=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Listar Notícias por Categoria
GET {{baseUrl}}/news?page=1&limit=10&category=Legislação
Content-Type: application/json

### Detalhe da Notícia
GET {{baseUrl}}/news/1
Content-Type: application/json

### Criar Notícia (Autenticado)
POST {{baseUrl}}/news
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Nova Notícia de Teste",
  "date": "2023-12-01",
  "category": "Comunidade",
  "content": "Conteúdo da nova notícia de teste para verificar a criação."
}

### Atualizar Notícia (Autenticado)
PUT {{baseUrl}}/news/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Título Atualizado"
}

### Desabilitar Notícia (Autenticado)
PATCH {{baseUrl}}/news/1/disable
Content-Type: application/json
Authorization: Bearer {{token}}

### Excluir Notícia (Autenticado)
DELETE {{baseUrl}}/news/1
Content-Type: application/json
Authorization: Bearer {{token}}
